### ISSUE TITLE
CocoaPod update after iOS8 tint (style) fix

### ISSUE THREAD

**Issue by th3m477** [AlvaroFranco/AFBlurSegue#12]
As per title, please can you update the pod spec with a newer version now that the iOS8 tint style has been exposed? Thanks!

**Comment by Zhukn1** [comment]
+1, please, please!

**Comment by Ponf** [comment]
Temporary solution is to specify commit:
```
pod 'AFBlurSegue', :git => 'https://github.com/AlvaroFranco/AFBlurSegue', :commit => '0efebb014f68c58675b03d51e475e6c6384c1fa9'
```

**Comment by Zhukn1** [comment]
@AlvaroFranco any update on this? can you please bump the pod version?

**Comment by AlvaroFranco** [comment]
Sorry guys! I'm really busy with my finals

**Comment by Zhukn1** [comment]
thanks man! 🍻👍🏼
