### ISSUE TITLE
Black tint

### ISSUE THREAD

**Issue by SolomonBier** [AlvaroFranco/AFBlurSegue#8]
Awesome custom segue! Is there a way to make a this segue have a black tint? Right now I'm changing the tint color but it doesn't affect anything. It just looks like a blurred window (clear).

Realizing this may be an issue for iOS 8 where you can't customize segs

**Comment by SolomonBier** [comment]
FYI, for those interested, for now you have to use iOS presets.  Change line below for simple fix-though not as custom 

 UIVisualEffect *visualEffect = [UIBlurEffect effectWithStyle:UIBlurEffectStyleDark];

**Comment by AlvaroFranco** [comment]
Yup, if you use it on iOS 8 the effects applied over -prepareForSegue: doesn't get applied since it uses UIBlurEffect. Changing it to UIBlurEffectStyleDark does the trick

**Comment by SolomonBier** [comment]
I ended up commenting out the if else statement for iOS7. Any reason you went with the native UIBlurEffectStyle over a customizable style?

**Comment by Zhukn1** [comment]
We can probably close this issue now.
